import calendar
jan = calendar.TextCalendar(calendar.SUNDAY)
feb = calendar.TextCalendar(calendar.SUNDAY)
mar = calendar.TextCalendar(calendar.SUNDAY)
apr = calendar.TextCalendar(calendar.SUNDAY)
mey = calendar.TextCalendar(calendar.SUNDAY)
jun = calendar.TextCalendar(calendar.SUNDAY)
jul = calendar.TextCalendar(calendar.SUNDAY)
agu = calendar.TextCalendar(calendar.SUNDAY)
sep = calendar.TextCalendar(calendar.SUNDAY)
okt = calendar.TextCalendar(calendar.SUNDAY)
nov = calendar.TextCalendar(calendar.SUNDAY)
des = calendar.TextCalendar(calendar.SUNDAY)


bulan = input ("Silahkan Masukan Bulan:")
if bulan=="1" : print (jan.prmonth (2022,1))
if bulan=="2" : print (feb.prmonth (2022,2))
if bulan=="3" : print (mar.prmonth (2022,3))
if bulan=="4" : print (apr.prmonth (2022,4))
if bulan=="5" : print (may.prmonth (2022,5))
if bulan=="6" : print (jun.prmonth (2022,6))
if bulan=="7" : print (jul.prmonth (2022,7))
if bulan=="8" : print (agu.prmonth (2022,8))
if bulan=="9" : print (sep.prmonth (2022,9))
if bulan=="10" : print (okt.prmonth (2022,10))
if bulan=="11" : print (nov.prmonth (2022,11))
if bulan=="12" : print (des.prmonth (2022,12))


